version: '3.8'

services:
  web:
    build: .
    image: autorelease-web-app:latest
    container_name: autorelease_app
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_VERSION=v1.0.0
    restart: always
